# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:16.15
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - run:
          name: Run linters
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
  build:
    docker:
      - image: cimg/node:16.15
    working_directory: ~/great-equalizer-backend
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --omit=dev
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/great-equalizer-backend
          paths:
            - node_modules
            - dist

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /^\d+.\d+.\d+$/
            branches:
              ignore: /.*/
          requires:
            - test
      - aws-ecr/build-and-push-image:
          attach-workspace: true
          workspace-root: ~/great-equalizer-backend
          filters:
            tags:
              only: /^\d+.\d+.\d+$/
            branches:
              ignore: /.*/
          requires:
            - build
          repo: great-equalizer-backend
          tag: "${CIRCLE_TAG}"
